### ISSUE TITLE
server-0.12.5.jar terminates with exception

### ISSUE THREAD

**Issue by bretskee** [blynkkk/blynk-server#107]
Hi,

server-0.12.4.jar installed and working without error

upgraded to 0.12.5 with the  following result:

sudo java -jar /usr/bin/blynk/server-0.12.5.jar -dataFolder /home/pi/Blynk
Exception in thread "main" java.lang.NullPointerException
        at cc.blynk.server.admin.http.handlers.IpFilterHandler.<init>(IpFilterHandler.java:26)
        at cc.blynk.server.admin.http.HttpsAdminServer.<init>(HttpsAdminServer.java:50)
        at cc.blynk.server.launcher.ServerLauncher.<init>(ServerLauncher.java:48)
        at cc.blynk.server.launcher.ServerLauncher.main(ServerLauncher.java:80)

Any help would be appreciated. Thanks.

**Comment by doom369** [comment]
Nice catch. Thank you for reporting. I updated build.
