### ISSUE TITLE
Local blynk server (server-0.41.4.jar) - Facebook login not working

### ISSUE THREAD

**Issue by phucluke** [blynkkk/blynk-server#1313]
I got the following error from my local Blynk server (server-0.41.4.jar). Please help to check. Thanks.

13:30:46.948 ERROR- Error performing facebook request. Token EAAWkCbFnFmgBAIVHGmkUjV98ovMCUzqEGziTrMVNUu1ZB13E5yPD8SD68mQLVsiEEZBW1ZBmxcs4eKB7KRj3GzemFX2uIBSYlHlr4N8cZBBZBKA05PxFvt7th8m8r2WnfdZBUxJzS3QkqaGppGYtji0oKattN2SNbOt9roqDyS0JquVdv2bKWEMijYnZB95769CQ2TZCEUhWMgZDZD for user xxxxxxx@gmail.com. Reason : General OpenSslEngine problem
13:30:46.948 DEBUG- Unexpected I/O exception on channel [id: 0x351f191d, L:/172.31.21.245:48756 ! R:graph.facebook.com/31.13.71.1:443]
java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200) ~[?:?]
        at java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120) ~[?:?]
        at java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104) ~[?:?]
        at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:86) ~[?:?]
        at sun.security.validator.Validator.getInstance(Validator.java:181) ~[?:?]
        at sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:308) ~[?:?]
        at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:176) ~[?:?]
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:249) ~[?:?]
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:141) ~[?:?]
        at io.netty.handler.ssl.ReferenceCountedOpenSslClientContext$ExtendedTrustManagerVerifyCallback.verify(ReferenceCountedOpenSslClientContext.java:242) ~[server-0.41.4.jar:?]
        at io.netty.handler.ssl.ReferenceCountedOpenSslContext$AbstractCertificateVerifier.verify(ReferenceCountedOpenSslContext.java:670) ~[server-0.41.4.jar:?]
        at io.netty.internal.tcnative.SSL.readFromSSL(Native Method) ~[server-0.41.4.jar:?]
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.readPlaintextData(ReferenceCountedOpenSslEngine.java:577) ~[server-0.41.4.jar:?]
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1141) ~[server-0.41.4.jar:?]
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1256) ~[server-0.41.4.jar:?]
        at io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:212) ~[server-0.41.4.jar:?]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1330) ~[server-0.41.4.jar:?]
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1225) ~[server-0.41.4.jar:?]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1272) ~[server-0.41.4.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[server-0.41.4.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[server-0.41.4.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[server-0.41.4.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[server-0.41.4.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[server-0.41.4.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[server-0.41.4.jar:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) ~[server-0.41.4.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[server-0.41.4.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[server-0.41.4.jar:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) ~[server-0.41.4.jar:?]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:796) ~[server-0.41.4.jar:?]
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:382) ~[server-0.41.4.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[server-0.41.4.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[server-0.41.4.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:333) ~[server-0.41.4.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[server-0.41.4.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[server-0.41.4.jar:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
13:30:46.948 DEBUG- Channel Closed: [id: 0x351f191d, L:/172.31.21.245:48756 ! R:graph.facebook.com/31.13.71.1:443] with attribute DISCARD

**Comment by doom369** [comment]
@phucluke hello. This is know java issue. You need to update your system to the latest version where java is fixed.

`do-release-upgrade`
