### ISSUE TITLE
Shutdown hook sometimes fails. Update log4j2 to 2.7.1 when released.

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-server#306]
```
azureuser@blynk-qa:~$ Exception in thread "pool-1-thread-1" Catch shutdown hook.
java.lang.NoClassDefFoundError: org/apache/logging/log4j/message/ParameterizedMessageStopping servers...

        at org.apache.logging.log4j.message.ParameterizedNoReferenceMessageFactory.newMessage(ParameterizedNoReferenceMessageFactory.java:104)
        at org.apache.logging.log4j.message.AbstractMessageFactory.newMessage(AbstractMessageFactory.java:75)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2010)
        at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1884)
        at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:793)
        at org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry.run(DefaultShutdownCallbackRegistry.java:74)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.message.ParameterizedMessage
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more
Shutting down Hardware plain tcp/ip server...
Exception in thread "Thread-1" java.lang.NoClassDefFoundError: io/netty/channel/AbstractChannelHandlerContext$13
        at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:620)
        at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:475)
        at io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:964)
        at io.netty.channel.AbstractChannel.close(AbstractChannel.java:234)
        at cc.blynk.server.core.BaseServer.close(BaseServer.java:69)
        at cc.blynk.server.hardware.HardwareServer.close(HardwareServer.java:64)
        at cc.blynk.server.workers.ShutdownHookWorker.run(ShutdownHookWorker.java:37)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: io.netty.channel.AbstractChannelHandlerContext$13
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 8 more

```

**Comment by johnou** [comment]
@doom369 did you find the root cause of this?

**Comment by doom369** [comment]
@johnou nope, it never happens on production, but often reproduced on QA, so I think it could be something env. specific.

**Comment by johnou** [comment]
@doom369 what env do you have on QA? I stumbled across an exception during my build process and your exception looked similar..

```text
[INFO] [INFO] BUILD SUCCESS
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] Total time: 02:02 min
[INFO] [INFO] Finished at: 2016-10-11T17:14:03+03:00
[INFO] [INFO] Final Memory: 87M/1387M
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] Exception in thread "pool-3-thread-1" java.lang.NoClassDefFoundError: org/apache/logging/log4j/message/ParameterizedMessage
[INFO] 	at org.apache.logging.log4j.message.ParameterizedNoReferenceMessageFactory.newMessage(ParameterizedNoReferenceMessageFactory.java:104)
[INFO] 	at org.apache.logging.log4j.message.AbstractMessageFactory.newMessage(AbstractMessageFactory.java:75)
[INFO] 	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2010)
[INFO] 	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1884)
[INFO] 	at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:793)
[INFO] 	at org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry.run(DefaultShutdownCallbackRegistry.java:76)
[INFO] 	at java.lang.Thread.run(Thread.java:745)
[INFO] Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.message.ParameterizedMessage
[INFO] 	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
[INFO] 	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
[INFO] 	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
[INFO] 	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
[INFO] 	... 7 more
[INFO] Cleaning up after release...
```

**Comment by johnou** [comment]
If I had to guess I would say that somehow log4j-core made its way onto the classpath, registered a shutdown hook in the JVM and log4j-api is not on the classpath..

**Comment by johnou** [comment]
Actually that makes no sense at all since ParameterizedNoReferenceMessageFactory is there..

**Comment by johnou** [comment]
@jglick could you offer some insight as to what might be going on?

**Comment by doom369** [comment]
@johnou the funny thing is that it is same as in prod :). Ubuntu 14.04. I didn't have a chance to spend enough time on find a root reason :(.

**Comment by Rajind** [comment]
https://issues.apache.org/jira/browse/LOG4J2-1642

**Comment by johnou** [comment]
@doom369 fyi I debugged the issue and found the cause, details are in the JIRA above.

**Comment by doom369** [comment]
@johnou nice. Thank you for letting me know.
