### ISSUE TITLE
Investigate possible memory leak

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-server#414]
![screenshot from 2016-12-28 18-55-25](https://cloud.githubusercontent.com/assets/1536494/21526772/4e628062-cd2f-11e6-9d4f-8df914157cb9.png)

```
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 452984839, max: 468189184)
        at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:614) ~[server-0.21.3_2.jar:?]
        at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:568) ~[server-0.21.3_2.jar:?]
        at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:686) ~[server-0.21.3_2.jar:?]
        at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:675) ~[server-0.21.3_2.jar:?]
        at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:237) ~[server-0.21.3_2.jar:?]
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:213) ~[server-0.21.3_2.jar:?]
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:141) ~[server-0.21.3_2.jar:?]
        at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:262) ~[server-0.21.3_2.jar:?]
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179) ~[server-0.21.3_2.jar:?]
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:170) ~[server-0.21.3_2.jar:?]
        at io.netty.handler.ssl.SslHandler.allocate(SslHandler.java:1455) ~[server-0.21.3_2.jar:?]
        at io.netty.handler.ssl.SslHandler.allocateOutNetBuf(SslHandler.java:1469) ~[server-0.21.3_2.jar:?]
        at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:519) ~[server-0.21.3_2.jar:?]
        at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:497) ~[server-0.21.3_2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:786) ~[server-0.21.3_2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:778) ~[server-0.21.3_2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:759) ~[server-0.21.3_2.jar:?]
        at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) ~[server-0.21.3_2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:786) ~[server-0.21.3_2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:812) ~[server-0.21.3_2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:824) ~[server-0.21.3_2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:804) ~[server-0.21.3_2.jar:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1027) ~[server-0.21.3_2.jar:?]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:301) ~[server-0.21.3_2.jar:?]
        at cc.blynk.server.core.model.auth.Session.sendToApps(Session.java:181) ~[server-0.21.3_2.jar:?]
        at cc.blynk.server.core.model.auth.Session.sendToApps(Session.java:168) ~[server-0.21.3_2.jar:?]
        at cc.blynk.server.hardware.handlers.hardware.logic.HardwareLogic.messageReceived(HardwareLogic.java:95) ~[server-0.21.3_2.jar:?]
        at cc.blynk.server.hardware.handlers.hardware.HardwareHandler.messageReceived(HardwareHandler.java:71) ~[server-0.21.3_2.jar:?]
        at cc.blynk.server.hardware.handlers.hardware.HardwareHandler.messageReceived(HardwareHandler.java:35) ~[server-0.21.3_2.jar:?]
        at cc.blynk.server.handlers.BaseSimpleChannelInboundHandler.channelRead(BaseSimpleChannelInboundHandler.java:55) ~[server-0.21.3_2.jar:?]

```

**Comment by doom369** [comment]
Seems like related https://github.com/netty/netty/issues/5723

**Comment by doom369** [comment]
Possible reason : 

> GET /websocket HTTP/1.1
> Connection: Upgrade
> Upgrade: websocket
> Host: blynk-cloud.com:8082
> Sec-WebSocket-Version: 13
> Sec-WebSocket-Key: MTMtMTQ4Mzc0MDQ1MTk1NQ==
> Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
> content-length: 0 that reached at the tail of the pipeline. Please check your pipeline configuration.
> 17:11:14.345 DEBUG - Discarded inbound message HttpObjectAggregator$AggregatedFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: CompositeByteBuf(ridx: 0, widx: 0, cap: 0, components=0))
>

**Comment by doom369** [comment]
Fixed with switch to pooled byte buf allocator.

**Comment by doom369** [comment]
Fixed with https://github.com/netty/netty/issues/6221 and https://github.com/netty/netty/pull/6252
