### ISSUE TITLE
Admin UI in 0.12.1 is not accessible?

### ISSUE THREAD

**Issue by aperepel** [blynkkk/blynk-server#77]
Hi, it looks like I can't access the new admin ui via any means. I've tried all possible http/https schemes and ports with a local sever. Even generated my own certs.

The farthest I got was to get a warning about a self-signed cert from a browser, but after clicking `Proceed` I never get any response back from a server. The trace log on the server side just mentions connection closed, etc.

**Comment by doom369** [comment]
Hello. Please attach your admin.log and blynk.log.

**Comment by aperepel** [comment]
I must be missing something very basic. Trying to follow the https://github.com/blynkkk/blynk-server docs, although it looks like the actual UI port is at 8777, not 7443 (I get some spinning wait time on 8777, but no connection on 7443 at all).

Not much in the logs though. `admin.log` is empty.  Nothing outstanding in the `blynk.log`. Maybe it is worth reviewing instructions for Admin UI?
```
09:14:44.447 INFO  - Using data dir '/var/folders/3n/7mfstrz170l_qm4_lhw2d5r40000gn/T/blynk'
09:14:44.449 DEBUG - Starting reading user DB.
09:14:44.659 DEBUG - Reading user DB finished.
09:14:44.703 INFO  - Initializing mail transport. Username : example@gmail.com. SMTP host : smtp.gmail.com:587
09:14:44.889 DEBUG - hard.socket.idle.timeout = 15
09:14:44.890 INFO  - Plain tcp/ip hardware server port 8442.
09:14:44.890 INFO  - Enabling SSL for hardware.
09:14:45.341 INFO  - SSL hardware port 8441.
09:14:45.342 INFO  - Enabling HTTPS for hardware.
09:14:45.355 INFO  - HTTPS hardware server port 7443.
09:14:45.361 INFO  - Enabling SSL for application.
09:14:45.361 WARN  - Found server certificates but no client certificate for '/Users/agrande/projects/blynk' path. Using one way ssl.
09:14:45.370 DEBUG - app.socket.idle.timeout = 600
09:14:45.370 INFO  - Application server port 8443.
09:14:45.373 INFO  - Administration server port 8777.
09:15:20.368 TRACE - Application channel disconnect. [id: 0x97bbccb7, /0:0:0:0:0:0:0:1:65481 :> 0.0.0.0/0.0.0.0:8443]
09:15:20.368 TRACE - Application channel disconnect. [id: 0x24dda591, /0:0:0:0:0:0:0:1:65480 :> 0.0.0.0/0.0.0.0:8443]
09:15:20.567 TRACE - Application channel disconnect. [id: 0xc40ed0ca, /0:0:0:0:0:0:0:1:65482 :> 0.0.0.0/0.0.0.0:8443]
09:15:43.395 TRACE - Application channel disconnect. [id: 0x2f565160, /0:0:0:0:0:0:0:1:65485 :> 0.0.0.0/0.0.0.0:8443]
09:39:35.752 INFO  - Using data dir '/var/folders/3n/7mfstrz170l_qm4_lhw2d5r40000gn/T/blynk'
09:39:35.754 DEBUG - Starting reading user DB.
09:39:35.975 DEBUG - Reading user DB finished.
09:39:36.018 INFO  - Initializing mail transport. Username : example@gmail.com. SMTP host : smtp.gmail.com:587
09:39:36.208 DEBUG - hard.socket.idle.timeout = 15
09:39:36.208 INFO  - Plain tcp/ip hardware server port 8442.
09:39:36.208 INFO  - Enabling SSL for hardware.
09:39:36.662 INFO  - SSL hardware port 8441.
09:39:36.663 INFO  - Enabling HTTPS for hardware.
09:39:36.670 INFO  - HTTPS hardware server port 7443.
09:39:36.675 INFO  - Enabling SSL for application.
09:39:36.675 WARN  - Found server certificates but no client certificate for '/Users/agrande/projects/blynk' path. Using one way ssl.
09:39:36.681 DEBUG - app.socket.idle.timeout = 600
09:39:36.681 INFO  - Application server port 8443.
09:39:36.684 INFO  - Administration server port 8777.

```

**Comment by doom369** [comment]
It is 7443 if you didn't change server.properties file.
Do you use 0.12.1 version?

By default access to admin UI allowed only from local host. In order to change it you need to change property :
```
  allowed.administrator.ips=127.0.0.1
```

**Comment by aperepel** [comment]
Nah, this is the first thing I checked, no go... same story. Really confusing. Just a sanity check - does admin UI require any special action other than starting up the server.jar? There is an admin.jar which is probably for script automation. The fact that we have server-0.12.1, but admin 0.12.0 only - is it an issue at all?

While writing this I somehow managed to get it to spit out an error finally (in admin.log):

```
10:32:12.792 - GET : /admin
10:32:12.793 - Error handling static file.
java.lang.NullPointerException: value
	at io.netty.util.internal.ObjectUtil.checkNotNull(ObjectUtil.java:31)
	at io.netty.handler.codec.http.DefaultHttpHeaders.toCharSequence(DefaultHttpHeaders.java:393)
	at io.netty.handler.codec.http.DefaultHttpHeaders.set(DefaultHttpHeaders.java:212)
	at io.netty.handler.codec.http.DefaultHttpHeaders.set(DefaultHttpHeaders.java:204)
	at cc.blynk.server.handlers.http.admin.handlers.FileHandler.channelRead0(FileHandler.java:184)
	at cc.blynk.server.handlers.http.admin.handlers.FileHandler.channelRead0(FileHandler.java:31)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at cc.blynk.server.handlers.http.admin.AdminHandler.channelRead(AdminHandler.java:52)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:147)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
```

**Comment by aperepel** [comment]
Here are my headers from the Chrome's Dev Console, but I got the same stacktrace with a simple `curl -k  https://localhost:7443/admin` too.
```
Request URL:https://localhost:7443/admin
Request Headers
Provisional headers are shown
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
X-DevTools-Emulate-Network-Conditions-Client-Id:24C6B3D2-BDE8-4B56-9D20-B584AD90979F```

**Comment by doom369** [comment]
@aperepel show me please how do you run server.

**Comment by doom369** [comment]
Also what exactly Java version do you use?

**Comment by doom369** [comment]
Please try this one and tell me if it works for you https://github.com/blynkkk/blynk-server/releases/download/untagged-f679267430af6b41a061/server-0.12.2-SNAPSHOT.jar

**Comment by aperepel** [comment]
The URL gives 404

**Comment by doom369** [comment]
Any errors in log?

**Comment by aperepel** [comment]
Sorry, I meant the jar download URL you provided was broken.

**Comment by doom369** [comment]
Ah. ok. Try this one https://www.dropbox.com/s/bsxifkdpij5pyc7/server-0.12.2-SNAPSHOT.jar?dl=0

**Comment by aperepel** [comment]
Thank you, this one works :)

**Comment by tzapu** [comment]
for future reference i was only able to make it work (in the current released version 0.12.1 by doing the following
clearing 127.0.0.1 from ` allowed.administrator.ips=` if you just comment it all out, it won't work
entering the url in browser with https in front `https://domain.com:1885/admin` 
this enabled me to open admin, but it seem there s not authentification on it yet?

**Comment by blynkkk** [comment]
@tzapu Yes, there is no auth. This is because opening admin page for anyone outside exposes additional security risks, especially for open-source. So I decided to restrict access only by specific ips.

**Comment by tzapu** [comment]
hi, i appreciate that, but in my case for instance, i am working from multiple locations, all with dynamic ip s... might wanna think about this scenario as well. maybe just the chance to obfuscate the url so we can set it to some unique string? better than nothing...

**Comment by blynkkk** [comment]
ok. please create separate ticket for that. I'll add that.

**Comment by tzapu** [comment]
done

cheers
