### ISSUE TITLE
Local Server throws a log4j error after a while

### ISSUE THREAD

**Issue by aperepel** [blynkkk/blynk-server#78]
`server-0.12.2-SNAPSHOT.jar`

I had a board pushing data every minute to a local Blynk server. After a while (apparently, enough to accumulate some data), the server spits out the error below. Runtime seems to be ok, but I'm not sure what data is being lost when it fails to roll the file over.
```
2015-12-21 08:05:06,036 AsyncLogger-1 ERROR Unable to invoke factory method in class class org.apache.logging.log4j.core.appender.RollingFileAppender for element RollingFile. java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:136)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:813)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:753)
	at org.apache.logging.log4j.core.appender.routing.RoutingAppender.createAppender(RoutingAppender.java:152)
	at org.apache.logging.log4j.core.appender.routing.RoutingAppender.getControl(RoutingAppender.java:136)
	at org.apache.logging.log4j.core.appender.routing.RoutingAppender.append(RoutingAppender.java:110)
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:152)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:125)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:116)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:390)
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:378)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:362)
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:79)
	at org.apache.logging.log4j.core.async.AsyncLogger.actualAsyncLog(AsyncLogger.java:385)
	at org.apache.logging.log4j.core.async.RingBufferLogEvent.execute(RingBufferLogEvent.java:103)
	at org.apache.logging.log4j.core.async.RingBufferLogEventHandler.onEvent(RingBufferLogEventHandler.java:43)
	at org.apache.logging.log4j.core.async.RingBufferLogEventHandler.onEvent(RingBufferLogEventHandler.java:28)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: ManagerFactory [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory@346629f5] unable to create manager for [/data/<email address here>/1_v4.csv] with data [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$FactoryData@6d48f4b0]
	at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:73)
	at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:61)
	at org.apache.logging.log4j.core.appender.rolling.RollingFileManager.getFileManager(RollingFileManager.java:79)
	at org.apache.logging.log4j.core.appender.RollingFileAppender.createAppender(RollingFileAppender.java:193)
	... 25 more

2015-12-21 08:05:06,037 AsyncLogger-1 ERROR Unable to create Appender of type RollingFile
```

The contents of the data dir are as follows for the account:
```
history_1_v0_daily.bin
history_1_v0_hourly.bin
history_1_v0_minute.bin
history_1_v1_daily.bin
history_1_v1_hourly.bin
history_1_v1_minute.bin
history_1_v2_daily.bin
history_1_v2_hourly.bin
history_1_v2_minute.bin
history_1_v3_daily.bin
history_1_v3_hourly.bin
history_1_v3_minute.bin
history_1_v4_daily.bin
history_1_v4_hourly.bin
history_1_v4_minute.bin
history_1_v5_daily.bin
history_1_v5_hourly.bin
history_1_v5_minute.bin
```

**Comment by aperepel** [comment]
The filename it tries to generate rolls from V0 to V5 (these are the channels used in my code, seemingly). The error message seems to be losing prefix and suffix of the file.

**Comment by doom369** [comment]
Thank you for reporting. Is that full log?

**Comment by aperepel** [comment]
Yes, there's not much more, the pattern repeats. It somehow drop `history_` and `_minute/daily/hourly` part and generates an invalid filename to roll.

**Comment by doom369** [comment]
It's correct. there 2 type of files. one is *.bin files for history graph, second - csv with every command logged. csv is just for case when you need every command to be stored. it may be turned off via property. But it shouldn't fail. I'll check.

**Comment by aperepel** [comment]
Interesting. I don't see any csv files in this run. When you have a minute, maybe you could add a paragraph on csv and bin formats in the docs? Thanks!

```
├── logs
│   ├── admin.log
│   ├── archive
│   │   ├── blynk.log.2015-12-18
│   │   ├── blynk.log.2015-12-19
│   │   ├── stats.log.2015-12-18
│   │   ├── stats.log.2015-12-19
│   │   ├── stats.log.2015-12-20
│   │   ├── worker.log.2015-12-18
│   │   ├── worker.log.2015-12-19
│   │   └── worker.log.2015-12-20
│   ├── blynk.log
│   ├── stats.log
│   ├── users
│   │   └── <emails goes here>.log
│   └── worker.log
```

**Comment by doom369** [comment]
CSV is already described here http://docs.blynk.cc/#blynk-server-administration-ui-raw-data-storage

**Comment by aperepel** [comment]
Hmm, does it mean the raw data storage _never_ worked for me? Not a single csv file in the current dir and sub-dirs. I do have `enable.raw.data.store=true` in my server.properties.

**Comment by doom369** [comment]
Look like - yes. This bug could be introduced with 0.12.0 version.

**Comment by doom369** [comment]
Ok. I update log4j version. seems they have few fixes for rollover appender. Please try [this](https://www.dropbox.com/s/bsxifkdpij5pyc7/server-0.12.2-SNAPSHOT.jar?dl=0) build and tell me if it works for you (you need to remove all prev. logs, just to be sure).

**Comment by aperepel** [comment]
No dice, got the error on startup. Here's my tree after I start things up (I've deleted logs and data dirs before):
```
.
├── admin
│   └── static
│       ├── admin.html
│       ├── admin.js
│       ├── favicon.ico
│       └── node_modules
│           └── ng-admin
│               └── build
│                   ├── ng-admin.min.css
│                   └── ng-admin.min.js
├── admin-0.12.0.jar
├── data
│   ├── <account name here>
│   ├── daily_temp.bin
│   ├── hourly_temp.bin
│   └── minute_temp.bin
├── logs
│   ├── admin.log
│   ├── stats.log
│   └── worker.log
├── server-0.12.1.jar
├── server-0.12.2-SNAPSHOT.jar
├── server.crt
├── server.csr
├── server.key
├── server.pem
└── server.properties
```

**Comment by doom369** [comment]
Could you try to run jar with sudo? Just to make sure problem is not in access rights.

**Comment by aperepel** [comment]
Let me wipe everything and start afresh. Will need to recreate the dashboard and let it run overnight.

**Comment by doom369** [comment]
I was not able to reproduce locally. What OS do you have? Does sudo helps? Do you have enough space?

**Comment by doom369** [comment]
@aperepel I investigated a bit - look like it is access problem. Either provide access to those folder either run with sudo. Let me know if that helps.

**Comment by doom369** [comment]
@aperepel Any update? [Here](https://www.dropbox.com/s/bsxifkdpij5pyc7/server-0.12.2-SNAPSHOT.jar?dl=0) is also build with more debug info so I could check if that log4j specific exception.

**Comment by aperepel** [comment]
Things look good here. It must have been old stale data in some folders. After I cleaned up, I'm getting a csv log output immediately.
