### ISSUE TITLE
OTAHandler fix NPE

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-server#835]
```
16:05:41.910 ERROR - Error during file upload.
java.lang.NullPointerException: null
	at cc.blynk.core.http.handlers.OTAHandler.getParam(OTAHandler.java:102) ~[classes/:?]
	at cc.blynk.core.http.handlers.OTAHandler.afterUpload(OTAHandler.java:82) ~[classes/:?]
	at cc.blynk.core.http.handlers.UploadHandler.channelRead0(UploadHandler.java:116) [classes/:?]
	at cc.blynk.core.http.handlers.UploadHandler.channelRead0(UploadHandler.java:48) [classes/:?]
```

**Comment by doom369** [comment]
test issue. not time for it right now.
